name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature. Help us understand the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What problem does this feature solve? What's the pain point?
      placeholder: When I try to ... it's difficult because ...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How do you think this should work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: What other approaches have you thought about?

  - type: dropdown
    id: scope
    attributes:
      label: Area of the project
      options:
        - CLI commands
        - MCP server
        - IDE integration (agent rules)
        - Parser (auto-extraction)
        - VS Code extension
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Any other context, screenshots, or examples.
